version: 1.0.{build}
# branches to build
branches:
  # whitelist
  only:
  - qa
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true  
# Building script
install:
  - gem install sass
before_build:
- cmd: >-
    dotnet restore

    cd src/AMX101.Site/

    npm install
    
    
	xcopy %appveyor_build_folder%\src\script\* 	%appveyor_build_folder%\src\AMX101.Site\setup\aus\
    xcopy %appveyor_build_folder%\src\script\* 	%appveyor_build_folder%\src\AMX101.Site\setup\nz\
    xcopy %appveyor_build_folder%\src\script\* 	%appveyor_build_folder%\src\AMX101.Site\setup\sng\

    cd setup\aus
    npm install
    npm run make
    cd ..\..

    cd setup\nz
    npm install
    npm run make
    cd ..\..

    cd setup\sng
    npm install
    npm run make
    cd ..\..

    call %appveyor_build_folder%\src\AMX101.JsonExport\publish_export.cmd
    %appveyor_build_folder%\util\AMX101.JsonExport.exe

build_script:
- cmd: >-

    npm run build

    dotnet build %appveyor_build_folder%\src\AMX101.Site\project.json
    dotnet build %appveyor_build_folder%\src\AMX101.Site\project_desktop.json -r win7-x64

after_build:

- dotnet publish --output %appveyor_build_folder%\src\AMX101.Site\setup\aus\amx11-win32-x64\resources\app
- dotnet publish --output %appveyor_build_folder%\src\AMX101.Site\setup\nz\amx11-win32-x64\resources\app
- dotnet publish --output %appveyor_build_folder%\src\AMX101.Site\setup\sng\amx11-win32-x64\resources\app

- copy %appveyor_build_folder%\src\AMX101.Site\appsettings_aus.json %appveyor_build_folder%\src\AMX101.Site\setup\aus\amx11-win32-x64\resources\app
- copy %appveyor_build_folder%\src\AMX101.Site\appsettings_nz.json %appveyor_build_folder%\src\AMX101.Site\setup\nz\amx11-win32-x64\resources\app
- copy %appveyor_build_folder%\src\AMX101.Site\appsettings_sng.json %appveyor_build_folder%\src\AMX101.Site\setup\sng\amx11-win32-x64\resources\app
- xcopy %appveyor_build_folder%\util\Data\aus*.*  %appveyor_build_folder%\src\AMX101.Site\setup\aus\amx11-win32-x64\resources\app\Data\
- xcopy %appveyor_build_folder%\util\Data\nz*.*  %appveyor_build_folder%\src\AMX101.Site\setup\nz\amx11-win32-x64\resources\app\Data\
- xcopy %appveyor_build_folder%\util\Data\sng*.*  %appveyor_build_folder%\src\AMX101.Site\setup\sng\amx11-win32-x64\resources\app\Data\

# disable automatic tests to speed up deployment
test: off
artifacts:
- path: ./publish_aus
  name: AMX101.Site.AU
- path: ./publish_nz
  name: AMX101.Site.NZ
- path: ./publish_sng
  name: AMX101.Site.SNG

deploy:
# Deploying to a named environment
- provider: Environment
  name: MUD-WEB01
  
# Slack notifications
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: amx101
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true